language: python
cache: pip

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable

python:
   - "3.6"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

  - wget http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - google-chrome-stable --headless --disable-gpu

install:
   - pip install -r requirements.txt

script:
    - behave